apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  labels:
    app: java-app
spec:
  selector:
    matchLabels:
        app: java-app
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: 727245885999.dkr.ecr.eu-west-1.amazonaws.com/apptest:latest
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
